In [18]:
import numpy as np
import pandas as pd

In [6]:
arr = np.arange(1,31,3)

In [7]:
arr

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [8]:
arr[(arr>5) & (arr<25)]

array([ 7, 10, 13, 16, 19, 22])

In [10]:
omatrix = np.arange(1,31).reshape(-1,3)

In [11]:
omatrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [ ]:
which = [-1,0,1,2]

In [12]:
omatrix = np.arange(1,31).reshape(3,-1) # -1 mean 3 permanent row -1 columns changeable

In [13]:
omatrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [14]:
np.log10(100)

2.0

In [15]:
mix_data = [1,'cat',True]

In [16]:
x = np.array(mix_data)
x

array(['1', 'cat', 'True'], dtype='<U11')

In [19]:
y = pd.Series(mix_data)
y

0       1
1     cat
2    True
dtype: object