In [1]:
import numpy as np

In [2]:
arr = np.arange(25)

In [3]:
ranarr = np.random.randint(0,50,10)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
arr.shape

(25,)

In [7]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
ranarr

array([49,  6, 48, 44, 20,  4, 19, 31, 12, 32])

In [10]:
ranarr.max()

49

In [11]:
ranarr.min()

4

In [12]:
ranarr.argmax()

0

In [13]:
ranarr.argmin()

5

In [14]:
arr.shape

(25,)

In [15]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
arr.reshape(5,5).shape

(5, 5)

In [17]:
arr.shape

(25,)

In [19]:
arr.dtype

dtype('int32')

In [20]:
a = np.random.randint(10, size=10)
a

array([5, 7, 3, 6, 8, 9, 9, 5, 3, 2])

In [21]:
a.dtype

dtype('int32')

In [25]:
b = np.full((4,6), 2.2)
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [26]:
b.dtype

dtype('float64')

In [27]:
a.ndim

1

In [28]:
b.ndim

2

In [29]:
a.size

10

In [30]:
b.size

24

In [31]:
len(b)

4

In [39]:
x = np.array([1,2,3])

In [40]:
y = np.array([4,5,6])

In [35]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [36]:
x = np.array([1,2,4])

In [37]:
y = np.array([4,5,6])

In [38]:
np.concatenate([x,y])

array([1, 2, 4, 4, 5, 6])

In [42]:
x = np.array([1,2,3])

In [43]:
y = np.array([4,5,6])

In [44]:
z = np.array([7,8,9])

In [45]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.concatenate([x,z,y])

array([1, 2, 3, 7, 8, 9, 4, 5, 6])

In [47]:
np.concatenate([x,y,[10,11,12]])

array([ 1,  2,  3,  4,  5,  6, 10, 11, 12])

In [48]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [53]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [54]:
a, b, c = np.split(x,[3,5])

In [55]:
a

array([1, 2, 3])

In [56]:
b

array([99, 99])

In [57]:
c

array([3, 2, 1])

In [58]:
np.split(x,4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [62]:
m = np.arange(20).reshape(5,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [65]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
np.vsplit(m, 4) 

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [67]:
np.vsplit(m, 2) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [63]:
np.vsplit(m, [1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [64]:
np.vsplit(m, 5) # 5 satır sayısına bölünür olmalı

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [68]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [70]:
np.hsplit(m,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [71]:
np.hsplit(m,[4])

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

In [72]:
left, right = np.hsplit(m,[2])

In [73]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [74]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [75]:
v = np.array([2,1,4,3,5])

In [76]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [77]:
v

array([2, 1, 4, 3, 5])

In [78]:
a = np.sort(v)

In [79]:
a

array([1, 2, 3, 4, 5])

In [82]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [83]:
twoD = np.random.randint(5,100,(3,3))
twoD

array([[97, 57, 32],
       [18,  9, 51],
       [37,  9, 28]])

In [84]:
np.sort(twoD)

array([[32, 57, 97],
       [ 9, 18, 51],
       [ 9, 28, 37]])

In [85]:
np.sort(twoD,axis = 1)

array([[32, 57, 97],
       [ 9, 18, 51],
       [ 9, 28, 37]])

In [86]:
np.sort(twoD,axis = 0)

array([[18,  9, 28],
       [37,  9, 32],
       [97, 57, 51]])

Numpy Indexing And Selection

In [87]:
import numpy as np

In [88]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr[8]

8

In [90]:
arr[-1]

10

In [91]:
arr[1:5]

array([1, 2, 3, 4])

In [92]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [93]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [94]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [95]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [96]:
a = [0,  2,  4,  6,  8, 10]

In [97]:
a[0:3] = 100

TypeError: can only assign an iterable

In [98]:
a[0:3] = [100,100,100]

In [99]:
a

[100, 100, 100, 6, 8, 10]

In [101]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [104]:
slice_of_arr[:] = 99 

In [105]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [106]:
arr # Asssigning value of slice_of_arr changed main arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [107]:
arr_copy = arr.copy()

In [108]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [109]:
arr_copy[0:6] = [0,1,2,3,4,5]

In [110]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [114]:
arr_2d[0]

array([ 5, 10, 15])

In [115]:
arr_2d[2]

array([35, 40, 45])

In [116]:
arr_2d[0][0]

5

In [117]:
arr_2d[1][1]

25

In [118]:
arr_2d[1,1]

25

In [119]:
arr_2d[2,2]

45

In [121]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [122]:
arr_2d[:,1:2]

array([[10],
       [25],
       [40]])

In [124]:
arr_2d[:,1]

array([10, 25, 40])

In [125]:
arr_2d[1,1] = 55

In [130]:
arr_2d

array([[ 3, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [131]:
arr_2d[0,0] = 3.3 # Changed int value
arr_2d

array([[ 3, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [134]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [136]:
v[1]

3

In [137]:
id_list = [1,2,3]
v[id_list]

array([3, 6, 9])

In [138]:
arr2d = np.zeros((10, 10), dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [139]:
for i in range(10):
    arr2d[i] = i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [146]:
id_list = [2,4,6,8]

In [147]:
arr2d[id_list]

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [7]:
jj = np.arange(1,17).reshape((4,4))
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [151]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [152]:
jj[[0,2,3],[0,1,3]] # [0,0], [2,1],[3,3]

array([ 1, 10, 16])

In [154]:
jj[0:,[1,2]] # 0 to last row, 1 and 2 column

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [9]:
jj[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [10]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [11]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [12]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [14]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [16]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr[(arr!=3) & (arr!=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [21]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [24]:
arr / arr

<ipython-input-24-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [27]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [28]:
v - 1

array([0, 1, 2, 3, 4])

In [29]:
v * 5

array([ 5, 10, 15, 20, 25])

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [33]:
# Calculating exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [34]:
np.max(arr)

9

In [35]:
arr.max()

9

In [36]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [37]:
np.pi

3.141592653589793

In [38]:
np.sin(np.pi)

1.2246467991473532e-16

In [39]:
np.sin(np.pi/2)

1.0

In [40]:
np.tan(np.pi/4)

0.9999999999999999

In [41]:
np.log(arr)

<ipython-input-41-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [43]:
np.log10(1000)

3.0

In [44]:
v

array([1, 2, 3, 4, 5])

In [45]:
# v-1
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [46]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

In [47]:
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [48]:
x2

array([0., 1., 2.])

In [49]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [50]:
v

array([1, 2, 3, 4, 5])

In [51]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [52]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [53]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [54]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [56]:
np.absolute(np.array([-4]))

array([4])

In [57]:
v = np.array([1,1,2,2,3,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3, 3])

In [58]:
np.mean(v)

2.25

In [59]:
np.median(v)

2.5

In [61]:
v.sum()

18

In [62]:
v.min()

1

In [63]:
v.max()

3