In [1]:
import numpy as np
import pandas as pd

In [3]:
data = [1, 2, 39, 67, 90]

In [4]:
data

[1, 2, 39, 67, 90]

In [5]:
pd.DataFrame(data, columns = ["column-name"])

column-name
0            1
1            2
2           39
3           67
4           90

In [6]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [9]:
pd.DataFrame(data = m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [10]:
df = pd.DataFrame(data = m, columns = ["var1","var2","var3"])

In [11]:
df.head(2)

var1  var2  var3
0     1     2     3
1     4     5     6

In [12]:
df.tail(1)

var1  var2  var3
2     7     8     9

In [13]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [14]:
df.columns = ["new1","new2","nem3"]

In [15]:
df

new1  new2  nem3
0     1     2     3
1     4     5     6
2     7     8     9

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.shape

(3, 3)

In [18]:
df.ndim

2

In [19]:
df.size

9

In [20]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)

In [22]:
s1

array([5, 0, 1, 2, 2])

In [23]:
s2

array([8, 6, 4, 1, 7])

In [24]:
s3

array([5, 4, 0, 8, 0])

In [25]:
myDict = {"var1":s1,"var2":s2,"var3":s3}
myDict

{'var1': array([5, 0, 1, 2, 2]),
 'var2': array([8, 6, 4, 1, 7]),
 'var3': array([5, 4, 0, 8, 0])}

In [26]:
df1 = pd.DataFrame(myDict)
df1

var1  var2  var3
0     5     8     5
1     0     6     4
2     1     4     0
3     2     1     8
4     2     7     0

In [27]:
df1[1:3]

var1  var2  var3
1     0     6     4
2     1     4     0

In [28]:
df1.index = ["a","b","c","d","e"]

In [29]:
df1

var1  var2  var3
a     5     8     5
b     0     6     4
c     1     4     0
d     2     1     8
e     2     7     0

In [30]:
df1["b":"d"] # b and d label therefore d also shows

var1  var2  var3
b     0     6     4
c     1     4     0
d     2     1     8

In [31]:
"var2" in df1

True

In [32]:
"martin" in df1

False